#This dashboard uses stremalit library to show the results 
import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path
import time
from datetime import datetime, timedelta
import json
from streamlit_autorefresh import st_autorefresh

#Define format and isert title
st.set_page_config(
    page_title="Herramienta",
    page_icon="📈",
    layout="wide"
)

st.title("📊 DNeutral tool - dashboard para estrategias delta neutral")
st.subheader("Obtén una rentabilidad positiva abriendo largos y cortos en diferentes exchanges")

#We obtain the data generated by the backend in the volume
with open("/shared_data/data_api.json", "r", encoding="utf-8") as file:
    input = json.load(file)

dict_series=input["dict_series"]
dataset_resultante=input["dataset_resultante"]
timestamp=input["timestamp"]

#Convertimos el texto ISO a datetime y ajustamos una hora, lo formateamos a 'YYYY-MM-DD HH:MM' y lo metemos en un sidebar
ts_local = datetime.fromisoformat(timestamp) + timedelta(hours=1)
ts_str = ts_local.strftime("%Y-%m-%d %H:%M")
st.write(f"Última actualización: {ts_str}")

#Obtain the granularity selected by the user
granularidad=st.slider("Seleccione el rango de analisis", 1, 5)

#Create the table to show the results, we need pandas lib. Filter by the selected granularity
st.subheader("Tabla comprarativa resultados")
df = pd.DataFrame(dataset_resultante[f"periodo_{granularidad}"], columns=["LARGO 📈", "CORTO 📉", "APR % 🔼", "MONEDA 🪙"])
st.dataframe(df)

#Lets create the chart for a given coin and pair of dex
st.subheader("📈 Evolución de Fundings por Exchange y Moneda")

#Define the filters of the chart
exchanges = ["Hyperliquid-Paradex", "Hyperliquid-Lighter", "Paradex-Lighter"]
monedas = sorted({v["Moneda"] for v in dict_series.values()})

col1, col2 = st.columns(2)
selected_exchange = col1.selectbox("Selecciona Exchanges", exchanges)
selected_moneda = col2.selectbox("Selecciona Moneda", monedas)

exchange1, exchange2 = selected_exchange.split("-")

key1 = f"{selected_moneda}_{exchange1}"
key2 = f"{selected_moneda}_{exchange2}"

if key1 in dict_series and key2 in dict_series:
    data1 = dict_series[key1]
    data2 = dict_series[key2]

    df1 = pd.DataFrame({
        "Fecha": pd.to_datetime(data1["Fechas"], format="mixed"),
        "Funding": data1["Fundings"],
        "Exchange": exchange1
    })

    df2 = pd.DataFrame({
        "Fecha": pd.to_datetime(data2["Fechas"], format="mixed"),
        "Funding": data2["Fundings"],
        "Exchange": exchange2
    })

    df_plot = pd.concat([df1, df2])

    fig = px.line(
        df_plot,
        x="Fecha",
        y="Funding",
        color="Exchange",
        title=f"Funding Rate - {selected_moneda} ({exchange1} vs {exchange2})",
        template="plotly_dark"
    )

    st.plotly_chart(fig, use_container_width=True)

else: 
    pass

#Refresh the data every 90 seconds
count = st_autorefresh(interval=90000)
