FROM python:3.11-slim
WORKDIR /frontend_service
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8502
CMD ["streamlit", "run", "DASHBOARD.py", "--server.port=8502", "--server.address=0.0.0.0"]

#Exponemos un puerto del contenedor para poder acceder al la web corriendo dentro de el desde mi maquina (host)
#El mapeo de puertos se hace en el compose
